### ISSUE TITLE
trophy unlock problem

### ISSUE THREAD

**Issue by VictorGuHao** [soarqin/vita-rxcheat#1]
deemo（NNP版本）奖杯无法加载，三国无双next的奖杯最后两个加载不出来。麻烦大神更新，谢谢大神。

**Comment by soarqin** [comment]
For deemo please read my reply in #3 
And I will look into Shin Sangoku Musou NEXT's problem later

**Comment by soarqin** [comment]
fixed in v0.9

**Comment by VictorGuHao** [comment]
66666666666
