### ISSUE TITLE
Unity games do not work.

### ISSUE THREAD

**Issue by SilicaAndPina** [soarqin/vita-rxcheat#3]
Your code has no support for unity's shit way of loading trophys
thus no unity games will work . - .

**Comment by soarqin** [comment]
The project is mainly targeting memory modifying, adding extra codes for deep hooking multi-module games(e.g. U3D games) may break compatibilities to other games so that there is no schedule to fix it.

**Comment by soarqin** [comment]
fixed in v0.9
