### ISSUE TITLE
有一个个人需要的功能

### ISSUE THREAD

**Issue by wetor** [soarqin/vita-rxcheat#4]
希望能加入浏览全部内存的功能....如果比较麻烦就算了....仅仅是个人需要....如果大佬顺便能做一个就好了..

**Comment by soarqin** [comment]
下个版本会有dump内存的功能，虚拟内存分块列表的功能看情况，目前专心在做一些重构工作，完成后看时间安排吧

**Comment by wetor** [comment]
那就太好了

**Comment by soarqin** [comment]
v0.10已经加入dump内存功能
